<?php

namespace Laradic\Support\Logger;
 /**
 * Part of the Radic packges.
 * Licensed under the MIT license.
 *
 * @package     Laradic\Support\Logger
 * @author      Robin Radic
 * @license     MIT
 * @copyright   (c) 2011-2015, Robin Radic
 * @link        http://radic.mit-license.org
 */
use Illuminate\Foundation\Application;
use Log;
use Laradic\Support\Contracts\Logger;
use FirePHP;
/**
 * ChromeLogger
 *
 * @package Laradic\Support\Logger\ChromeLogger
 */
class FirelogLogger extends AbstractLogger
{

    /**
     * @var \FirePHP
     */
    protected $firelog;
    public function __construct(Application $app)
    {
        parent::__construct($app); // TODO: Change the autogenerated stub

        $this->firelog = FirePHP::getInstance(true);
    }

    public function log()
    {
        $args = func_get_args();
        $this->firelog->log(array_slice($args, 1), $args[0]);
    }

    public function debug()
    {
        $args = func_get_args();
        $this->firelog->log($args, 'DEBUG');
    }

    public function warn()
    {
        $args = func_get_args();
        $this->firelog->warn(array_slice($args, 1), $args[0]);
    }

    public function info()
    {
        $args = func_get_args();
        $this->firelog->info(array_slice($args, 1), $args[0]);
    }

    public function error()
    {
        $args = func_get_args();
        $this->firelog->error(array_slice($args, 1), $args[0]);
    }
}
